### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yarda** [drowe67/LPCNet#18]
Hi,

I am trying to package LPCNet into Fedora, but I am confused about the license. Is it BSD?
And what's the license of the model data (lpcnet_191005_v1.0.tgz)? What's the reason for the model data being hosted elsewhere?

In Fedora we are building packages offline in the sandbox, so we cannot download the model data during the build. If the license is compatible, I could predownload and bundle the model data, but I am curious what's the reason behind the split.

**Comment by yarda** [comment]
Also the CMakeLists.txt should be fixed to allow building with the model data extracted without downloading them - this doesn't seem possible at the moment. I can provide such patch in case the model data has FOSS compatible license.

**Comment by hobbes1069** [comment]
Hey Jaroslav! I was eventually going to package it for Fedora since I'm a developer on this project I just hadn't gotten around to it :) But if you really want to go ahead. If you want to. David I'm sure will pipe in with the model data info. I can't remember if that was setup before we transitioned to github?

**Comment by yarda** [comment]
Hi Richard, I know, in Fedora we maintain wsjtx together :)

Do you know what's the LPCNet project roadmap? I.e. whether it's planned to a) merge the code into codec2 or b) keep it separated in the LPCNet (or maybe under different name). I wonder, because I would like to get the FreeDV 2020 support into Quisk, where the FreeDV is now supported natively through the codec2 library.

**Comment by hobbes1069** [comment]
David is kind of the master here. It's a very small developer group. AFAIK it will stay a separate library. Also, unless it's changed, codec2 and LPCNet are cross dependent, so you have to build codec2, build LPCNet against it, and then rebuild codec2 against LPCNet. Small pain on the front end.

**Comment by yarda** [comment]
Thanks for info, I think it answered my question from the issue 19 which I can close now. We could add bootstrap support to the codec2 SPEC (bootstrap without LPCNet) or maybe we could build the LPCNet from the codec2 SPEC, i.e. build the codec2 in one build task (two phases). I am going to play with it and provide Fedora patches. What do you like more? I.e. separate LPCNet package or LPCNet built from the codec2 SPEC?

**Comment by hobbes1069** [comment]
Ok, I've been catching up on the project since my hiatus. It doesn't look like codec2 and LPCNet are cross dependent anymore so that's a good thing. I'll ping David about adding a license file to the model data but we can assume BSD for now.
