### ISSUE TITLE
LPCNET_VERSION_MINOR should be 2

### ISSUE THREAD

**Issue by ra1nb0w** [drowe67/LPCNet#21]
With the new release 0.2 the [following line](https://github.com/drowe67/LPCNet/blob/f491f66163eba21654c88894608bdad807de7b89/CMakeLists.txt#L40) should be `set(LPCNET_VERSION_MINOR 2)`

**Comment by hobbes1069** [comment]
Whoops, thanks for catching that. This was literally my 3rd "release" I've done on github. Will push a fix momentarily.
