### ISSUE TITLE
SSE support (for testing)

### ISSUE THREAD

**Issue by jg1uaa** [drowe67/LPCNet#24]
For performance reason, LPCNet (lpcnet_dec) requires AVX FMA instruction.
But cheap Intel processor (Pentium/Celeron) does not support AVX still now.

I tried SSE-vectorized LPCNet on OpenBSD-6.6/amd64 (clang 8.0.1) with AMD's A10-7860K processor PC, its performance barely achieved with enabling -msse4.1 clang option. Old SSE (SSE3 or former) SSE shown lower performance.

Testing code is at my repository, https://github.com/jg1uaa/LPCNet/ .
Can you evaluate SSE-vectorize is usable or not?

**Comment by drowe67** [comment]
Hi @jg1uaa - nice work :+1:  

Sure, I will check it out.

Can you please raise a pull request for your fork against https://github.com/drowe67/LPCNet?  That way I can easily see what you've changed.  We can maybe write some simple bench marks to compare with AVX.

**Comment by hobbes1069** [comment]
I believe the pull request was accepted. Closing
