### ISSUE TITLE
global structure causes crash when 2 using 2 channels

### ISSUE THREAD

**Issue by dave-g8kbb** [drowe67/LPCNet#32]
Hi David

Think I found another one (well, 2 actually).

First the main issue....
It's a bit like the one with codec2.
Quisk opens 2 channels. Buried in the code there is a data structure with a pointer. It's a static. Initialising it, it carefully checks to see if already initialised and if it is, skips doing it a second time, however when it is freed, there is no such check. This causes a pointer to memory to be freed that does not point to valid memory.
Details below.

The second one was a doozie. Occasional random crashes with avx in exp8_approx() in vec_avx.h with a segmentation error.
I finally found that if I inlined the function call, the problem vanished.
I changed this
static __m256 exp8_approx(__m256 X).........
to this
static inline __m256 exp8_approx(__m256 X).......
Then I went looking at the CPU. My processor is an AMD FX-6100. Checking the AMD website it does not support AVX or AVX2 but when the code tests to see if AVX is supported the result is yes. However I get the weird crashes but AVX instructions do in fact work! So it looks like AVX is supported by the FX-6100 but not without issues. For some reason inlining that function keeps it happy. Most weird. The function is only used 4 times so the code penalty is small and it increases 2020 mode support for these processors.

In regard of the bug....

In freq.c at line 51 this structure is defined:

typedef struct {
  int init;
  kiss_fft_state *kfft;
  float half_window[OVERLAP_SIZE];
  float dct_table[NB_BANDS*NB_BANDS];
} CommonState;

This is used to create a static structure at line 125:

CommonState common;

It’s initilialised and freed thus:

static void check_init() {
  int i;
  if (common.init) return;
  common.kfft = opus_fft_alloc_twiddles(WINDOW_SIZE, NULL, NULL, NULL, 0);
  for (i=0;i<OVERLAP_SIZE;i++)
    common.half_window[i] = sin(.5*M_PI*sin(.5*M_PI*(i+.5)/OVERLAP_SIZE) * sin(.5*M_PI*(i+.5)/OVERLAP_SIZE));
  for (i=0;i<NB_BANDS;i++) {
    int j;
    for (j=0;j<NB_BANDS;j++) {
      common.dct_table[i*NB_BANDS + j] = cos((i+.5)*j*M_PI/NB_BANDS);
      if (j==0) common.dct_table[i*NB_BANDS + j] *= sqrt(.5);
    }
  }
  common.init = 1;
}

void freq_close() {
    opus_fft_free(common.kfft,0);
}

If there are two open channels, then init is skipped on the second call because of common.init. 
However closing the second channel calls free() a second time with the already freed pointer. This causes a crash (probably compiler dependent).

A simple solution is to change the close function to make use of the init structure member thus:

void freq_close() {
  if( common.init ) {
    opus_fft_free(common.kfft,0);
    common.init = 0;
  }
}

Regards
Dave

**Comment by drowe67** [comment]
Thanks @dave-g8kbb, yes I've found the LPCnet init routines quite confusing myself, and recently fixed a similar issue that was causing memory leaks.  A lot of that code was prototyped by the original author in order to get some NN functionality quickly.

I don't think anyone has tried parallel instances to date - it has been enough of a struggle to get it to run at all in real time at all! Can you actually run two LPCNet decoders together at the same time?

Can you pls put your proposed fixes in the form of a Pull Request with actual C code changes?  That way they will get automatically tested, and are easy for me to check.

**Comment by drowe67** [comment]
@dave-g8kbb has this problem been resolved?
