### ISSUE TITLE
[Win32] Generating nnet_data.[ch]

### ISSUE THREAD

**Issue by gvanem** [drowe67/LPCNet#35]
I'm on Windows trying to build this library using a hacked up GNU-makefile (since Cmake fails).

In the process I need to generate `src/nnet_data.c` and `src/nnet_data.h` using the Python script `src/dump_lpcnet.py`.
I already managed to `pip install keras`, but the requirement `tensorflow` seems impossible:
```
Collecting tensorflow
  ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

What? How are we supposed to generate these files?

**Comment by hobbes1069** [comment]
Currently Win32 builds are typically cross-compiled from Linux using MinGW. What development tools are you using?

**Comment by gvanem** [comment]
I use clang-cl and MSVC-2019. But I found the needed files in this .tar-ball:
  https://media.xiph.org/lpcnet/data/lpcnet_data-8ea8396.tar.gz

**Comment by gvanem** [comment]
Trying to build Tensorflow myself using `vcpkg install tensorflow-cc:x86-windows`, gives me:
```
...
CMake Error at ports/tensorflow-cc/portfile.cmake:4 (message):
  TensorFlow does not support 32bit systems.
```
Thanks Google!
