### ISSUE TITLE
No compilation on RPi

### ISSUE THREAD

**Issue by dl1ycf** [drowe67/LPCNet#49]
In src/CMakeLists.txt you read

if(SSE OR AVX OR AVX2 OR CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
    add_executable(test_vec test_vec.c)
    target_link_libraries(test_vec m)
else()
    message(WARNING "No SSE/AVX/AVX2 CPU flags identified, not building test_vec.")
endif()

but this should replace

SSE   ==> SSE_PRESENT GREATER 0

in the if condition (the same for AVX and AVX2).

Note:
SSE  means: SSE is used if it is detected (is ON on non-SSE systems by default!)
SSE_PRESENT means: SSE is present (detected in /proc/cpuinfo)

consequence when compiling on a non-SSE system: test_vec.c is compiled and this results in errors
if no include file defines sgemv_accum16_fast.

With the indicated change, it compiles on my RPi.

P.S.: If __NEON__  were a standard cpp #define on my system, the problem would not have popped up.
But linking test_vec.c can only be done if one (or more) of the 

#ifdef __AVX__
#ifdef __AVX2__
#elif __SSE__
#elif __ARM_NEON__ || __aarch64__

evaluates "true".

**Comment by drowe67** [comment]
@dl1ycf thanks. There was some early work on getting this code to run on Pi 3s, however the CPU load was too high for real time operation so it's not a target that is being maintained.  I understand that Jean-Marc has made some progress in reducing CPU load in the original version of LPCNet, and operation on a Pi may now be possible.

**Comment by tmiw** [comment]
Actually, the correct solution would probably be to use the same checks as in the top-level CMakeLists.txt, i.e.

```
if(
    (${SSE} AND (${SSE_PRESENT} OR ${SSE_PRESENT} GREATER 0)) OR
    (${AVX} AND (${AVX_PRESENT} OR ${AVX2_PRESENT} GREATER 0)) OR
    (${AVX2} AND (${AVX2_PRESENT} OR ${AVX2_PRESENT} GREATER 0)) OR
    CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
add_executable(test_vec test_vec.c)
target_link_libraries(test_vec m)
else()
message(WARNING "No SSE/AVX/AVX2 CPU flags identified, not building test_vec.")
endif()
```

as if `X_PRESENT` is false we want to ignore whatever `X` is regardless. I wouldn't mind doing this change now but as @drowe67 said, you're likely not going to have a good time unless the upstream optimizations are brought in.

**Comment by tmiw** [comment]
Just created a PR (see above) to fix this issue. Let me know if that works for you, @dl1ycf. 👍
