### ISSUE TITLE
a lower bit rate?

### ISSUE THREAD

**Issue by moseranliunian** [drowe67/LPCNet#53]
How should I modify to achieve a lower bit rate? I think your lowest bit rate is 1733? I would appreciate it if you could share your solution

**Comment by drowe67** [comment]
Study the examples in the README, e.g. https://github.com/drowe67/LPCNet#fully-quantised-encoderdecoder-programs

**Comment by moseranliunian** [comment]
Maybe I'm a little stupid and can't understand how to achieve it all. Could you explain more ?

**Comment by tmiw** [comment]
Looks like the decimate option in `lpcnet_enc` and `lpcnet_dec` would be what controls that if I'm understanding the current docs correctly.

Anyway, this should probably be continued in the Discussions section but it doesn't look like that's there right now. @drowe67, can that section be added or should we just use codec2's?

**Comment by drowe67** [comment]
I've enabled discussions.
